name: Java App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Choose 'temurin', 'zulu', 'adopt', etc.
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package
      working-directory: demo/src

    - name: List target directory to verify JAR creation
      run: |
        echo "Checking contents of target directory:"
        ls demo/src/target || echo "target directory not found"
        echo "Checking if JAR file exists:"
        ls demo/src/target/*.jar || echo "JAR file not found"

    - name: Build Docker Image
      run: docker build -t java-docker-app .
      working-directory: demo/src

    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag java-docker-app:latest venkatreddy290/java-docker-app:latest
        docker push venkatreddy290/java-docker-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'

    - name: Helm Install/Upgrade
      run: |
        helm upgrade --install java-app ./helm/java-app-chart --set image.repository=venkatreddy290/java-docker-app --set image.tag=latest --namespace default
