name: Java App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker Image
      run: docker build -t java-docker-app .

    - name: Push Docker Image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag java-docker-app:latest yourdockerhubusername/java-docker-app:latest
        docker push yourdockerhubusername/java-docker-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'

    - name: Helm Install/Upgrade
      run: |
        helm upgrade --install java-app ./helm/java-app-chart --set image.repository=yourdockerhubusername/java-docker-app --set image.tag=latest --namespace default
